### ISSUE TITLE
bossbar command not working

### ISSUE THREAD

**Issue by KickSquareMC** [4drian3d/TitleAnnouncer#17]
The bossbar command arguments aren't working, no matter what I try:
`/vsendbossbar KickSquare 10 RED NOTCHED_6 test` -> INVALID ARGUMENT
`/vannouncebossbar 10 RED NOTCHED_6 Test` -> INVALID ARGUMENT

Am I doing something wrong or are the bossbar commands just not working?

**Comment by 4drian3d** [comment]
> The bossbar command arguments aren't working, no matter what I try: `/vsendbossbar KickSquare 10 RED NOTCHED_6 test` -> INVALID ARGUMENT `/vannouncebossbar 10 RED NOTCHED_6 Test` -> INVALID ARGUMENT
> 
> Am I doing something wrong or are the bossbar commands just not working?

The format that the plugin has accepts the values 6, 10, 12, 12, 20, full
In the next update I will change that to accept NOTCHED_*
